spring.application.name=registration-service

server.port=8083

spring.datasource.url=jdbc:postgresql://ep-green-leaf-a1o5umvg-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_I1sOkDdWHC9G

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
spring.docker.compose.enabled=false

eureka.client.enabled=false


