server.port=8080

spring.application.name=api-gateway

# Auth Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Event Service
spring.cloud.gateway.routes[1].id=event-service
spring.cloud.gateway.routes[1].uri=lb://event-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/events/**

# Registration Service
spring.cloud.gateway.routes[2].id=registration-service
spring.cloud.gateway.routes[2].uri=lb://registration-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/registrations/**

spring.cloud.gateway.routes[3].id=registration-payments
spring.cloud.gateway.routes[3].uri=lb://registration-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/payments/**

spring.cloud.gateway.routes[4].id=registration-receipts
spring.cloud.gateway.routes[4].uri=lb://registration-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/receipts/**

# ===============================
# JWT Configuration (must match auth_service)
# ===============================
jwt.secret=mySuperSecretKeyWithAtLeast256BitsLength


spring.security.user.name=admin
spring.security.user.password=admin
# ===============================
# Disable Eureka (IMPORTANT for now)
# ===============================
eureka.client.enabled=true
spring.cloud.discovery.enabled=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/